### PR TITLE
dump each constraint after both related tables were defined

### PR DESCRIPTION
**Pull request by konjoot**
I found a more convenient solution with no need to dumping all backref foreing keys to the bottom of schema.

### CODE REVIEW

**Comment by ronen** [comment]
@knjoot Thanks!!  Seeing your failing example, I now think I understand the problem with the algorithm.  
And while there may be more elegant ways to fix it, I'd like to accept your fix.

...but your PR still includes changes to:

    lib/schema_plus/active_record/connection_adapters/schema_statements.rb
    spec/named_schemas_spec.rb

which are unrelated to this issue.  Could you edit your commit to not include those (make a separate PR for them, maybe?).  

Or if you don't want to bother making more changes, I'm happy to split the PR apart myself and get your backref fixes in -- but then the commit will have my name on it rather than yours won't get listed as a contributor by github.      Let me know which you prefer.

Thanks again for tracking down the problem and solution!

**Comment by konjoot** [comment]
Yes, I can revert changes from:

    lib/schema_plus/active_record/connection_adapters/schema_statements.rb
    spec/named_schemas_spec.rb

I made those changes because without it postgresql specs fails on Ubuntu with russian locale.
I'll push this changes in near time. And if you can prompt me more elegant solution, I'll try to implement it too.

**Comment by ronen** [comment]
> I did them because without it postgresql specs fails on Ubuntu with russian locale

A PR to fix those would be great

>  And if you can prompt me more elegant solution, I'll try to implement it too.

I don't know how easy or hard it would be...   here's what I was thinking about trying to do.   Before your fix, the schema was looking like (excerpted):

```ruby
create_table "grade_systems", force: :cascade do |t|
    t.string  "name"
    t.integer "school_id"
    t.integer "parent_id"
    t.integer "profile_id"
end
add_foreign_key "grade_systems", ["parent_id"], "grade_systems", ["id"], :on_update => :no_action, :on_delete => :no_action, :name => "fk_grade_systems_parent_id"

create_table "schools", force: :cascade do |t|
    t.string  "name"
    t.integer "default_grade_system_id"
    t.foreign_key ["default_grade_system_id"], "grade_systems", ["id"], :on_update => :no_action, :on_delete => :no_action, :name => "fk_schools_default_grade_system_id"
end
add_foreign_key "buildings", ["school_id"], "schools", ["id"], :on_update => :no_action, :on_delete => :no_action, :name => "fk_buildings_school_id"
add_foreign_key "grade_systems", ["school_id"], "schools", ["id"], :on_update => :no_action, :on_delete => :no_action, :name => "fk_grade_systems_school_id"

 create_table "buildings", force: :cascade do |t|
     t.string  "name"
     t.integer "school_id"
 end
```
and after your fix, the schema looks like:

```ruby
create_table "grade_systems", force: :cascade do |t|
    t.string  "name"
    t.integer "school_id"
    t.integer "parent_id"
    t.integer "profile_id"
end
add_foreign_key "grade_systems", ["parent_id"], "grade_systems", ["id"], :on_update => :no_action, :on_delete => :no_action, :name => "fk_grade_systems_parent_id"

create_table "schools", force: :cascade do |t|
    t.string  "name"
    t.integer "default_grade_system_id"
    t.foreign_key ["default_grade_system_id"], "grade_systems", ["id"], :on_update => :no_action, :on_delete => :no_action, :name => "fk_schools_default_grade_system_id"
end

add_foreign_key "grade_systems", ["school_id"], "schools", ["id"], :on_update => :no_action, :on_delete => :no_action, :name => "fk_grade_systems_school_id"

 create_table "buildings", force: :cascade do |t|
     t.string  "name"
     t.integer "school_id"
 end
add_foreign_key "buildings", ["school_id"], "schools", ["id"], :on_update => :no_action, :on_delete => :no_action, :name => "fk_buildings_school_id"
```

That works of course, but to be a bit cleaner, ideally the foreign key for `"buildings"` would be defined inline rather than outside, i.e.:

```ruby
 create_table "buildings", force: :cascade do |t|
     t.string  "name"
     t.integer "school_id"
     t.foreign_key ["school_id"], "schools", ["id"], :on_update => :no_action, :on_delete => :no_action, :name => "fk_buildings_school_id"
 end
```

Your `fix_backref_fks_for(table)` method could possibly be changed to move the fk into `inline_fks[table]` and that might be all that's needed (unless there's some other bad case I haven't thought of).

But even more basically: why should it be necessary to "fix" the fk backref & inline lists while dumping? Ideally the code that breaks the cycles should create those lists correctly and put each fk where it belongs.    That would be the most elegant solution IMHO.

**Comment by konjoot** [comment]
All done, thanks for help.

**Comment by ronen** [comment]
@konjoot I finally looked at your fix -- wow!  That's amazing.  I never would have guessed that all it would take would be changing a `.first` to a `.last`   

Thanks for figuring that all out.  Just goes to show you can't measure the complexity of a bug fix by the number of lines of code :)

**Comment by ronen** [comment]
@knojoot FYI I've release version 1.8.7 with this fix in it.

**Comment by konjoot** [comment]
@ronen, thanks for your support, I was glad to help.

**Pull request merged**
