### PR TITLE
Move all backref foreign_key definitions at the bottom of schema.rb

### PR DESCRIPTION
**Pull request by konjoot**
Sometimes in complicated DB's schemas may be situation when add_foreign_key definition appears before one of the involved table is defined, and consequently schema load fails.

### CODE REVIEW

**Comment by ronen** [comment]
Thanks for the PR.  Can you write a spec that evokes the case where (without your change) the backref foreign key definition comes out too soon?  The current algorithm is supposed to avoid doing that!  Though of course it may have a bug.

I'd somewhat like to continue to emit the backref foreign keys definitions immediately after both tables are defined if possible, rather than have them all at the end.  Though admittedly that's not crucial if it can't be done easily.  But in any case having a spec to make sure that backrefs detection algorithm is behaving properly would be a good thing.

Also some technicalities: the PR has an extra commit; and git is unable to merge the files.   Could you merge/rebase against the 1.x branch?

Thanks again

**Comment by konjoot** [comment]
Ok, take me a little time. And thanks for quick response.

**Comment by konjoot** [comment]
I have some difficulties with merge\rebase against 1.x branch, because I made my commits on master, and some changes in it relate to 2.x release and override changes in 1.x branch. May be I should make new pull request to 1.x branch? Sorry for stupid question, but this is my first pull request.

**Comment by ronen** [comment]
@konjoot yes, the master branch is now being used for 2.x development, and 1.x branch is stable.

So if you can make your changes to (a branch off of) the 1.x branch and do a pull request, that would probably be best.

Sorry for the branch confusion, thanks for trying to work through it.

**Comment by konjoot** [comment]
I close this pull request, because of [new one](https://github.com/SchemaPlus/schema_plus/pull/203).

**Pull request closed without merging**
