### PR TITLE
Allow one table to reference another table multiple times

### PR DESCRIPTION
**Pull request by lowjoel**
See comments in e887cd9c19ed2784873e52086cfb876518d57427.

### CODE REVIEW

**Comment by ronen** [comment]
Ooh that's a bad bug -- Good catch & fix!

BTW I'm thinking now that there's no real need to support AR 4.2.0 ; anyone who's using 4.2.0 ought to be able to upgrade to 4.2.1, and it seems ugly to muddy up the code.   But I'll go ahead and merge this (thought first se my comment on 9e0d7defd696cb112a0f23a140cd33be29bc65ef) and then later on I'll get rid of the 4.2.0 support.

**Comment by ronen** [comment]
@lowjoel actually don't bother re my comment on 9e0d7defd696cb112a0f23a140cd33be29bc65ef -- as long as I had things open I merged your PR then added the extra line in the test myself.

And I've release 2.0.0.pre15 with this fix in it.

**Comment by ronen** [comment]
oops!  I released too soon!  gaah that's what happens when i'm in a rush.  with the extra test in it, the build fails.  i could've sworn that I tested that locally and it worked before I pushed.

I've gotta run now, care to pull it down and see what's up?

**Comment by ronen** [comment]
@lowjoel got back online, got it.  it was a bug in the spec. 

I had added the line to test for   `reference(:users, :id).on(:user_id)`, but the table didn't actually have that column in it!  So there was actually only one foreign key in the spec.   I added `t.integer :user_id references: :user` to the spec, and verified that before your fix the spec failed and with your fix in the new release, the spec succeeds.

So all's good.

**Comment by lowjoel** [comment]
Haha, you got back before I did.

Thanks for the fix. Releasing 2.0.0.pre16?

Also, are the foreign keys stuff scheduled for extraction to a separate gem?

**Comment by ronen** [comment]
No need to release pre16 for this, since it's just in the spec; the pre15 code is gode

Yeah, the foreign keys stuff is going to be two gems:  schema_plus_foreign_key and schema_auto_foreign_key. they're in progress on my computer (nothing pushed yet) but i've been too busy lately to wrap them up.  once those are done, schema_plus 2.0 can go out of pre-release.

**Comment by lowjoel** [comment]
ah yes, silly me.

**Pull request merged**
