### PR TITLE
set default name in add_foreign_key method

### PR DESCRIPTION
**Pull request by kushkella**
Fixes https://github.com/SchemaPlus/schema_plus/issues/216

### CODE REVIEW

**Comment by ronen** [comment]
@kushkella thanks!

Do you have anything else pending, or should I go ahead and release 2.0.0.pre14?  (I was a bit too quick off the mark with 2.0.0.pre13 :)

**Comment by kushkella** [comment]
I think I've fixed all issues that I came across :) I know of another issue but it isn't breaking anything so far. I'll create an issue for the problem, but please go ahead and release a new version. Thanks!

**Comment by ronen** [comment]
OK, 2.0.0.pre14 is released.   Thanks again for jumping in and fixing things

...and looking forward (kindof :) to the other issue you've found.

**Comment by kushkella** [comment]
I really appreciate your prompt response and quick release of the new version of gem. Thanks a lot!

**Pull request merged**
